import test from 'node:test';
import assert from 'node:assert/strict';
import { startApp, testConfig, mockFetch, fixtures } from './helpers.mjs';
import { consentTextVersion } from '../lib/notifications.mjs';

test('v1 contracts: catchments, forecast, exposure, scenarios, model-status', async t => {
  const ctx = await startApp();
  t.after(ctx.close);
  const { client } = ctx;
  const health = await client('/api/health'); assert.equal(health.status, 200); assert.equal(health.json.floodProbability, 'null until calibrated');
  assert.equal((await client('/api/ready')).json.status, 'ready');
  const list = await client('/api/v1/catchments');
  assert.equal(list.status, 200); assert.equal(list.json.type, 'FeatureCollection'); assert.equal(list.json.features.length, 10); assert.equal(list.json.coordinateOrder, 'longitude,latitude');
  assert.ok(list.json.provenance.catchments.sha1); assert.ok(list.headers.get('x-request-id'));
  assert.equal((await client('/api/v1/catchments/nowhere')).status, 404);
  assert.equal((await client('/api/v1/catchments/kedarnath/rivers')).json.features.length > 0, true);
  const forecast = await client('/api/v1/catchments/kedarnath/forecast');
  assert.equal(forecast.status, 200);
  const f = forecast.json;
  assert.equal(f.catchmentId, 'kedarnath'); assert.ok(['demonstration', 'experimental'].includes(f.mode)); assert.notEqual(f.mode, 'validated'); assert.equal(f.issuedAt, '2026-09-10T18:00:00.000Z');
  assert.ok(/Z$/.test(f.validFrom)); assert.equal(f.times.length, 16); assert.equal(f.stepSeconds, 10800); assert.equal(f.nativeResolutionM, 25000);
  assert.ok(f.floodProbability.every(v => v === null)); assert.equal(f.precipitationMm[5], 1.5, 'missing cell excluded, not zeroed');
  assert.equal(f.soilVolumetricM3M3.length, 4); assert.equal(f.soilVolumetricM3M3[0].unit, 'm³/m³');
  assert.equal(f.models.length, 3); assert.equal(f.models[2].ensemble.memberCount, 3);
  assert.equal(f.discharge.status, 'available'); assert.equal(f.smapL4.status, 'missing');
  assert.ok(f.provenance.length >= 5 && f.limitations.length >= 4 && Array.isArray(f.qualityFlags));
  const again = await client('/api/v1/catchments/kedarnath/forecast');
  assert.equal(again.json.models[0].servedFrom, 'archive', 'second call is served from the archived run');
  const runs = await client('/api/v1/catchments/kedarnath/runs'); assert.equal(runs.json.runs.length, 3);
  const exposure = await client('/api/v1/catchments/kedarnath/exposure');
  assert.equal(exposure.status, 200); assert.equal(exposure.json.population.totalPopulation, 12346); assert.equal(exposure.json.population.referenceYear, 2020);
  assert.equal(exposure.json.builtUp.status, 'not-ingested'); assert.equal(exposure.json.builtUp.fractionOfArea, null); assert.equal(exposure.json.terrain.status, 'available');
  const shelters = await client('/api/v1/catchments/kedarnath/shelters'); assert.equal(shelters.json.count, 0); assert.equal(shelters.json.status, 'no-authoritative-dataset');
  const status = await client('/api/v1/model-status');
  assert.equal(status.json.mode === 'demonstration' || status.json.mode === 'experimental', true); assert.equal(status.json.floodProbabilityAvailable, false);
  assert.equal(status.json.dataFreshness.ecmwf_ifs025.issuedAt, '2026-09-10T18:00:00.000Z'); assert.equal(status.json.weatherNext.weatherNext3.status, 'not-configured');
  assert.ok(status.json.knownLimitations.length >= 4);
  const sources = await client('/api/v1/sources'); assert.equal(sources.json.soil.credentials, 'not configured'); assert.equal(sources.json.soil.discovery.latestGranules[0].granuleId.startsWith('SMAP_L4'), true);
});
test('scenarios live in the research namespace, validate input and honour idempotency keys', async t => {
  const ctx = await startApp(); t.after(ctx.close); const { client } = ctx;
  const body = { name: 'Saturated monsoon', catchmentId: 'gangtok', assumedSoilSaturationFraction: 0.9, rainfallOverrideMmPerHour: 40, modelInputs: { slopeDeg: 30 } };
  const created = await client('/api/v1/scenarios', { method: 'POST', body, headers: { 'Idempotency-Key': 'scenario-key-001' } });
  assert.equal(created.status, 201); assert.equal(created.json.scenario.namespace, 'research-scenario'); assert.equal(created.json.scenario.notAnAdvisory, true); assert.equal(created.json.scenario.floodProbability, null);
  assert.equal(created.json.scenario.demonstrationIndex.isProbability, false);
  const replay = await client('/api/v1/scenarios', { method: 'POST', body, headers: { 'Idempotency-Key': 'scenario-key-001' } });
  assert.equal(replay.status, 201); assert.equal(replay.json.scenario.id, created.json.scenario.id); assert.equal(replay.headers.get('idempotent-replayed'), 'true');
  const conflict = await client('/api/v1/scenarios', { method: 'POST', body: { ...body, name: 'Other' }, headers: { 'Idempotency-Key': 'scenario-key-001' } });
  assert.equal(conflict.status, 422);
  assert.equal((await client('/api/v1/scenarios', { method: 'POST', body: { ...body, assumedSoilSaturationFraction: 2 } })).status, 400);
  assert.equal((await client('/api/v1/scenarios', { method: 'POST', body: { ...body, catchmentId: 'mars' } })).status, 404);
  assert.equal((await client(`/api/v1/scenarios/${created.json.scenario.id}`)).json.scenario.name, 'Saturated monsoon');
  assert.equal((await client('/api/v1/scenarios?catchmentId=gangtok')).json.scenarios.length, 1);
  const bad = await fetch(ctx.base + '/api/v1/scenarios', { method: 'POST', headers: { 'Content-Type': 'text/plain' }, body: 'x' }); assert.equal(bad.status, 415);
});
test('input validation and security headers on point routes and static files', async t => {
  const ctx = await startApp(); t.after(ctx.close); const { client } = ctx;
  assert.equal((await client('/api/weather?lat=50&lon=79')).status, 400);
  assert.equal((await client('/api/weather?lat=abc&lon=79')).status, 400);
  assert.equal((await client('/api/weather?lat=30.7&lon=79.1')).status, 200);
  assert.equal((await client('/api/places?q=x')).status, 400);
  assert.equal((await client('/api/places?q=Gangtok')).json.results[0].state, 'Sikkim');
  assert.equal((await client('/api/compare?lat=30.7&lon=79.1')).json.models.length, 3);
  const page = await client('/'); assert.equal(page.status, 200); assert.match(page.headers.get('content-security-policy'), /default-src 'self'/); assert.equal(page.headers.get('x-frame-options'), 'DENY');
  assert.equal((await client('/.env')).status, 403); assert.equal((await client('/../package.json')).status, 404);
  assert.equal((await client('/api/nope')).status, 404);
  assert.equal((await client('/api/v1/catchments', { method: 'POST', body: {} })).status, 405);
  const big = await fetch(ctx.base + '/api/v1/scenarios', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: 'x'.repeat(70000) }) }); assert.equal(big.status, 413);
});
test('provider failure paths: stale archive and stale weather cache are labeled, total outage is 502', async t => {
  const fx = fixtures();
  let fail = false;
  const fetchImpl = mockFetch(fx, { 'api.open-meteo.com/v1/forecast': u => { if (fail) throw new Error('down'); return u.searchParams.get('models') === 'ecmwf_ifs025' ? fx.ifs : u.searchParams.get('models') === 'ecmwf_aifs025_single' ? fx.aifs : fx.weather; }, 'ensemble-api.open-meteo.com/v1/ensemble': () => { if (fail) throw new Error('down'); return fx.ensemble; } });
  const ctx = await startApp({ fetchImpl }); t.after(ctx.close); const { client } = ctx;
  const first = await client('/api/v1/catchments/manali/forecast'); assert.equal(first.status, 200);
  const weather = await client('/api/weather?lat=32.2&lon=77.2'); assert.equal(weather.status, 200);
  fail = true;
  ctx.app.store.cache.set('meta:ecmwf_ifs025', { issuedAt: '2026-09-11T00:00:00.000Z' }, 60); // newer run announced, provider down
  const second = await client('/api/v1/catchments/manali/forecast');
  assert.equal(second.status, 200); assert.equal(second.json.models[0].servedFrom, 'archive'); assert.equal(second.json.models[0].stale, true);
  assert.ok(second.json.limitations.some(l => /archive/.test(l)));
  ctx.app.store.cache.set('weather:32.200,77.200', weather.json, 0);
  const staleWeather = await client('/api/weather?lat=32.2&lon=77.2'); assert.equal(staleWeather.json.servedFrom, 'stale-cache');
  const fresh = await client('/api/v1/catchments/ooty/forecast'); assert.equal(fresh.status, 200, 'GloFAS still available → not a total outage');
  assert.equal(fresh.json.models.every(m => m.status === 'unavailable'), true); assert.equal(fresh.json.times.length, 0);
});
test('notifications: consent, verification, authority approval, held deliveries, idempotent queue, cancel, unsubscribe', async t => {
  const ctx = await startApp({ config: testConfig({ ADVISORY_AUTHORITY_KEY: 'authority-key-123' }) }); t.after(ctx.close); const { client } = ctx;
  const noConsent = await client('/api/v1/subscriptions', { method: 'POST', body: { channel: 'sms', address: '+919999900001', language: 'en', catchmentId: 'kedarnath', consent: { accepted: false } } }); assert.equal(noConsent.status, 400);
  assert.equal((await client('/api/v1/subscriptions', { method: 'POST', body: { channel: 'sms', address: '9999900001', language: 'en', catchmentId: 'kedarnath', consent: { accepted: true, textVersion: consentTextVersion } } })).status, 400);
  const sub = await client('/api/v1/subscriptions', { method: 'POST', body: { channel: 'sms', address: '+919999900001', language: 'hi', catchmentId: 'kedarnath', consent: { accepted: true, textVersion: consentTextVersion } }, headers: { 'Idempotency-Key': 'sub-key-0001' } });
  assert.equal(sub.status, 201); assert.equal(sub.json.subscription.status, 'pending-verification'); assert.equal(sub.json.subscription.addressMasked, '+91…01'); assert.match(sub.json.verification.delivery, /not sent/);
  const replay = await client('/api/v1/subscriptions', { method: 'POST', body: { channel: 'sms', address: '+919999900001', language: 'hi', catchmentId: 'kedarnath', consent: { accepted: true, textVersion: consentTextVersion } }, headers: { 'Idempotency-Key': 'sub-key-0001' } });
  assert.equal(replay.json.subscription.id, sub.json.subscription.id);
  const id = sub.json.subscription.id;
  assert.equal((await client(`/api/v1/subscriptions/${id}/verify`, { method: 'POST', body: { code: '000000' } })).status, 400);
  assert.equal((await client(`/api/v1/subscriptions/${id}/verify`, { method: 'POST', body: { code: sub.json.verification.devVerificationCode } })).json.subscription.status, 'active');
  const draft = await client('/api/v1/advisories', { method: 'POST', body: { catchmentId: 'kedarnath', authority: 'District Emergency Operations Centre (test)', issuedAt: '2026-09-12T05:00:00Z', expiresAt: '2026-09-12T17:00:00Z', affectedArea: 'Mandakini valley', recommendedAction: 'Move to higher ground', officialLink: 'https://example.org/warning/1' } });
  assert.equal(draft.status, 201); assert.equal(draft.json.advisory.status, 'draft'); assert.ok(draft.json.advisory.previews.hi.includes('चेतावनी')); assert.ok(draft.json.advisory.previews.en.includes('https://example.org/warning/1'));
  assert.equal((await client('/api/v1/advisories', { method: 'POST', body: { catchmentId: 'kedarnath', authority: 'x', issuedAt: '2026-09-12T05:00:00Z', expiresAt: '2026-09-12T04:00:00Z', affectedArea: 'a', recommendedAction: 'b', officialLink: 'http://insecure' } })).status, 400);
  const advId = draft.json.advisory.id;
  assert.equal((await client(`/api/v1/advisories/${advId}/approve`, { method: 'POST', body: {} })).status, 401);
  assert.equal((await client(`/api/v1/advisories/${advId}/approve`, { method: 'POST', body: {}, headers: { Authorization: 'Bearer wrong' } })).status, 401);
  const approved = await client(`/api/v1/advisories/${advId}/approve`, { method: 'POST', body: { approvedBy: 'Duty officer' }, headers: { Authorization: 'Bearer authority-key-123' } });
  assert.equal(approved.status, 200); assert.equal(approved.json.advisory.status, 'issued'); assert.equal(approved.json.deliveries.recipients, 1); assert.equal(approved.json.deliveries.created, 1); assert.match(approved.json.deliveries.status, /held/);
  assert.equal((await client(`/api/v1/advisories/${advId}/approve`, { method: 'POST', body: {}, headers: { Authorization: 'Bearer authority-key-123' } })).status, 409, 'cannot approve twice');
  const deliveries = await client(`/api/v1/advisories/${advId}/deliveries`); assert.equal(deliveries.json.deliveries[0].status, 'held');
  const update = await client('/api/v1/advisories', { method: 'POST', body: { catchmentId: 'kedarnath', authority: 'DEOC (test)', issuedAt: '2026-09-12T06:00:00Z', expiresAt: '2026-09-12T18:00:00Z', affectedArea: 'Mandakini valley', recommendedAction: 'Updated action', officialLink: 'https://example.org/warning/2', supersedes: advId } });
  const approvedUpdate = await client(`/api/v1/advisories/${update.json.advisory.id}/approve`, { method: 'POST', body: {}, headers: { Authorization: 'Bearer authority-key-123' } });
  assert.equal(approvedUpdate.status, 200); assert.equal((await client(`/api/v1/advisories/${advId}`)).json.advisory.status, 'superseded');
  const cancelled = await client(`/api/v1/advisories/${update.json.advisory.id}/cancel`, { method: 'POST', body: { reason: 'test' }, headers: { Authorization: 'Bearer authority-key-123' } });
  assert.equal(cancelled.json.advisory.status, 'cancelled'); assert.ok(cancelled.json.cancellationMessagePreview.hi);
  assert.equal((await client(`/api/v1/advisories/${update.json.advisory.id}/deliveries`)).json.deliveries[0].status, 'cancelled');
  const unsub = await client(`/api/v1/subscriptions/${sub.json.unsubscribeToken}`, { method: 'DELETE' }); assert.equal(unsub.json.subscription.status, 'unsubscribed');
  const status = await client('/api/v1/notifications/status'); assert.equal(status.json.sendsEnabled, false); assert.equal(status.json.subscriptions.unsubscribed, 1);
  assert.equal((await client('/api/v1/audit')).status, 503, 'audit needs an admin key');
  const audit = ctx.app.store.audit.list(50); assert.ok(audit.some(e => e.action === 'advisory.approve') && audit.some(e => e.action === 'subscription.create'));
  assert.equal(JSON.stringify(audit).includes('+919999900001'), false, 'audit log never contains phone numbers');
});
test('approval is disabled entirely when no authority key is configured', async t => {
  const ctx = await startApp(); t.after(ctx.close); const { client } = ctx;
  const draft = await client('/api/v1/advisories', { method: 'POST', body: { catchmentId: 'ooty', authority: 'Test', issuedAt: '2026-09-12T05:00:00Z', expiresAt: '2026-09-12T17:00:00Z', affectedArea: 'Nilgiris', recommendedAction: 'Test', officialLink: 'https://example.org/w' } });
  assert.equal((await client(`/api/v1/advisories/${draft.json.advisory.id}/approve`, { method: 'POST', body: {}, headers: { Authorization: 'Bearer anything' } })).status, 503);
});
